### ISSUE TITLE
Does it runs on WIndows?

### ISSUE THREAD

**Issue by Suleman-Elahi** [aryaminus/saram#1]
I tried it using on Windows 10 and the installation was unsuccessful. In the end it throws an error:
![image](https://user-images.githubusercontent.com/24384996/37266259-535e0c62-2576-11e8-96a2-0e8b414a31eb.png)

Any tips to make it run on Windows ?

**Comment by aryaminus** [comment]
Try executing `saram \path\to\dir` should work. It was a dependency for english-dictionary for Arch. Should work. I will also upload a updated version
