### ISSUE TITLE
Request: write extracted text to .jpg or .pdf

### ISSUE THREAD

**Issue by kevinchr** [aryaminus/saram#3]
Hey,

i'm not sure if you accept requests, but i guess it doesn't harm to ask :)

I was wondering if it is possible to rewrite image filename with extracted text data from pytesseract to .jpg

So for example i have an image with the filename 'abc.jpg' and text on the image 'this is an apple' , OCR the image and then the image and filename becomes 'this is an  apple.jpg

Really hope you can implement this on saram :)

Thank you for reading my request

**Comment by aryaminus** [comment]
So you want the Initial sentence to be written as the filename in case the image has more paragraph? I have used sub-process to call `tesseract` and in your case I would have to import it as a module and save it accordingly. Will look forward to it.

**Comment by kevinchr** [comment]
Hey, 

Yes indeed that would be awesome... Most images/memes have 140 characters or less... I attached an image to give you an idea 
![imageabc](https://user-images.githubusercontent.com/10005359/39319869-b576231e-4982-11e8-9a8a-472a47233e36.jpg)

And thank you very much for making this happen :)

**Comment by aryaminus** [comment]
Sure. Give me some time to work on it as I am busy with deadline projects.Will create a new package instead and update you here

**Comment by kevinchr** [comment]
I understand and thank you in advance :)

**Comment by aryaminus** [comment]
[Memento](https://github.com/aryaminus/memento) I created the python program, will publish in pypi in coming days

**Comment by kevinchr** [comment]
Thank you so much aryaminus i really look forward to try out your script :) Kudos to you
